from datetime import datetime

import pytest
from pl_tiny_clients.constants import SYSTEM_TIMEZONE

ARBITRARY_DATETIME = datetime.fromtimestamp(
    946684800, tz=SYSTEM_TIMEZONE
)  # January 1, 2000 at 00:00:00 in the system timezone
DEFAULT_DATETIME = ARBITRARY_DATETIME

PYTEST_INTEGRATION_MARKER = pytest.mark.integration
PYTEST_DEPENDENT_MARKER = pytest.mark.dependent
PYTEST_MANUAL_MARKER = pytest.mark.manual

PYTEST_INTEGRATION_TEST_MARKERS = [
    PYTEST_INTEGRATION_MARKER,
    PYTEST_DEPENDENT_MARKER,
    PYTEST_MANUAL_MARKER,
]

PYTEST_MANUAL_MARKERS = [
    PYTEST_INTEGRATION_MARKER,
    PYTEST_DEPENDENT_MARKER,
    PYTEST_MANUAL_MARKER,
]
